spring.application.name=stock-backend
# ===============================
# CONFIGURACIÓN DE POSTGRESQL
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# Le dice a Spring el dialecto exacto de Postgres a usar
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# MAGIA PURA: "update" lee tus entidades Java y crea/modifica las tablas automáticamente en la DB
#spring.jpa.hibernate.ddl-auto=update

# Para ver en la consola el código SQL que Spring genera por detrás (súper útil para debugear)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true